/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.11
 * Generated at: 2022-01-07 21:19:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name = \"viewport\" content = \"width=divice-width\", initial-scale=\"1\">\n");
      out.write("<link rel = \"stylesheet\" href = \"css/bootstrap.css\">\n");
      out.write("<link rel = \"stylesheet\" href = \"css/custom.css\">\n");
      out.write("<title>대장금</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<nav class =\"navbar navbar-default\">\n");
      out.write("		<div class = \"navbar-header\">\n");
      out.write("			<button type = \"button\" class = \"navbar-toggle collapsed\"\n");
      out.write("				data-toggle = \"collapse\" data-target = \"#bs-example-navbar-collapse-1\"\n");
      out.write("				aria-expanded=\"false\">\n");
      out.write("				<span class = \"icon-bar\"></span>\n");
      out.write("				<span class = \"icon-bar\"></span>\n");
      out.write("				<span class = \"icon-bar\"></span>\n");
      out.write("			</button>\n");
      out.write("			<a class=\"navbar-brand\" href = \"main.jsp\">대학생 장학금 찾아주기 : 대장금</a>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("			<ul class = \"nav navbar-nav\">\n");
      out.write("				<li><a href=\"https://portal.sungshin.ac.kr/sso/login.jsp\">성신여대</a></li>\n");
      out.write("				<li><a href=\"http://www.kosaf.go.kr/\">한국장학재단</a></li>\n");
      out.write("				<li><a href=\"https://rule.sungshin.ac.kr/service/law/lawView.do?seq=95&historySeq=0&gubun=cur&tree=part\">성신장학규정</a></li>\n");
      out.write("			</ul>\n");
      out.write("			<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("				<li class=\"dropdown\">\n");
      out.write("					<a href=\"#\" class=\"dropdown-toggle\"\n");
      out.write("						data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\n");
      out.write("						aria-expanded=\"false\">접속하기<span class=\"caret\"></span></a>\n");
      out.write("					<ul class=\"dropdown-menu\">\n");
      out.write("						<li><a href = \"login.jsp\">로그인 </a></li>\n");
      out.write("						<li class=\"active\"><a href=\"join.jsp\">회원가입</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	<div class=\"container\">\n");
      out.write("      <div class=\"col-lg-4\"></div>\n");
      out.write("      <div class=\"col-lg-4\">\n");
      out.write("         <div class=\"jumbotron\" style=\"padding-top:20px;\">\n");
      out.write("            <form method=\"post\" action=\"joinAction.jsp\">\n");
      out.write("               <h3 style=\"text-align:center;\">대장금 회원가입</h3>\n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" placeholder=\"학번\" name=\"userID\" maxlength=\"10\">\n");
      out.write("               </div>\n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                  <input type=\"password\" class=\"form-control\" placeholder=\"비밀번호\" name=\"userPassword\" maxlength=\"20\">\n");
      out.write("               </div>\n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" placeholder=\"이름\" name=\"userName\" maxlength=\"20\">\n");
      out.write("               </div>\n");
      out.write("               <div class=\"form-group\">\n");
      out.write("               	  <input type=\"Email\" class=\"form-control\" placeholder=\"이메일\" name=\"userEmail\" maxlength=\"30\">\n");
      out.write("               </div>\n");
      out.write("               <div class=\"form-group\">\n");
      out.write("               <select name=\"dept\" onchange=\"changeDpt(this)\">\n");
      out.write("                        <option value=\"none\" selected disabled>학부</option>\n");
      out.write("                        <option value=\"인문과학대학\">인문과학대학</option>\n");
      out.write("                        <option value=\"사회과학대학\">사회과학대학</option>\n");
      out.write("                        <option value=\"법과대학\">법과대학</option>\n");
      out.write("                        <option value=\"자연과학대학\">자연과학대학</option>\n");
      out.write("                        <option value=\"지식서비스공과대학\">지식서비스공과대학</option>\n");
      out.write("                        <option value=\"간호대학\">간호대학</option>\n");
      out.write("                        <option value=\"Health&WellnessCollege\">Health&Wellness College</option>\n");
      out.write("                        <option value=\"뷰티생활산업국제대학\">뷰티 생활산업 국제대학</option>\n");
      out.write("                        <option value=\"사범대학\">사범대학</option>\n");
      out.write("                        <option value=\"미술대학\">미술대학</option>\n");
      out.write("                        <option value=\"음악대학\">음악대학</option>\n");
      out.write("                        <option value=\"융합문화예술대학\">융합 문화 예술 대학</option>  \n");
      out.write("               </select>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("                    <select name=\"userMajor\" id=\"userMajor\">\n");
      out.write("                        <option selected disabled>학과</option>\n");
      out.write("                    </select>\n");
      out.write("                </div> \n");
      out.write("                ");
      out.write("\n");
      out.write("               <h5>학년</h5>\n");
      out.write("               <div class=\"form-group\" style=\"text-align:center;\">\n");
      out.write("                  <div class=\"btn-group\" data-toggle=\"buttons\">\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type = \"radio\" name=\"userYear\" autocomplete=\"off\" value=\"1\" checked>1학년\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type = \"radio\" name=\"userYear\" autocomplete=\"off\" value=\"2\">2학년\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type = \"radio\" name=\"userYear\" autocomplete=\"off\" value=\"3\">3학년\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type = \"radio\" name=\"userYear\" autocomplete=\"off\" value=\"4\">4학년\n");
      out.write("                     </label>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" placeholder=\"학점\" name=\"userGrade\" maxlength=\"10\">\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" placeholder=\"어학성적\" name=\"userLgrade\" maxlength=\"10\">\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <h5>다자녀 유무</h5>\n");
      out.write("               <div class=\"form-group\" style=\"text-align:center;\">\n");
      out.write("                  <div class=\"btn-group\" data-toggle=\"buttons\">\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type = \"radio\" name =\"userMchild\" autocomplete=\"off\" value=\"cO\" checked>다자녀O\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type = \"radio\" name =\"userMchild\" autocomplete=\"off\" value=\"cX\">다자녀X\n");
      out.write("                     </label>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("               <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" placeholder=\"소득분위\" name=\"userIncome\" maxlength=\"10\">\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <h5>멘토링 유무</h5>\n");
      out.write("               <div class=\"form-group\" style=\"text-align:center;\">\n");
      out.write("                  <div class=\"btn-group\" data-toggle=\"buttons\">\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type=\"radio\" name=\"userMentor\" autocomplete=\"off\" value=\"mO\" checked>멘토링O\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type = \"radio\" name=\"userMentor\" autocomplete=\"off\" value=\"mX\">멘토링X\n");
      out.write("                     </label>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <h5>봉사 등급</h5>\n");
      out.write("               <div class=\"form-group\" style=\"text-align:center;\">\n");
      out.write("                  <div class=\"btn-group\" data-toggle=\"buttons\">\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type=\"radio\" name=\"userVol\" autocomplete=\"off\" value=\"Vx\" checked>해당없음\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type=\"radio\" name=\"userVol\" autocomplete=\"off\" value=\"Va\">A\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type=\"radio\" name=\"userVol\" autocomplete=\"off\" value=\"Vb\">B\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type=\"radio\" name=\"userVol\" autocomplete=\"off\" value=\"Vc\">C\n");
      out.write("                     </label>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               <h5>국가고시 여부</h5>\n");
      out.write("               <div class=\"form-group\" style=\"text-align:center;\">\n");
      out.write("                  <div class=\"btn-group\" data-toggle=\"buttons\">\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type=\"radio\" name=\"userExam\" autocomplete=\"off\" value=\"Ex\" checked>국가고시 해당없음\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type=\"radio\" name=\"userExam\" autocomplete=\"off\" value=\"E9\">9급 이상\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type=\"radio\" name=\"userExam\" autocomplete=\"off\" value=\"E7\">7급 이상\n");
      out.write("                     </label>\n");
      out.write("                     <label class=\"btn btn-primary active\">\n");
      out.write("                        <input type=\"radio\" name=\"userExam\" autocomplete=\"off\" value=\"E5\">5급 이상\n");
      out.write("                     </label>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("               <input type=\"submit\" class=\"btn btn-primary form-control\" value=\"회원가입\">\n");
      out.write("            </form>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-lg-4\"></div>\n");
      out.write("   </div>\n");
      out.write("		<div class=\"col-lg-4\"></div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<script>\n");
      out.write("    function changeDpt(e) {\n");
      out.write("        var humanities = [\"국어국문학과\", \"영어영문학과\", \"독일어문/문화학과\", \"프랑스어문/문화학과\", \"일본어문/문화학과\", \"중국어문/문화학과\", \"사학과\"];\n");
      out.write("        var historic = [\"정치외교학과\", \"심리학과\", \"지리학과\", \"경제학과\", \"미디어커뮤니케이션학과\", \"경영학부\", \"사회복지학과\"];\n");
      out.write("        var law = [\"법학부\"];\n");
      out.write("        var nature = [\"수리통계 데이터사이언스 학부\", \"화학/에너지융합학부\"];\n");
      out.write("        var engineering = [\"서비스디자인공학과\", \"융합보안공학과\", \"컴퓨터공학과\", \"청정융합에너지공학과\", \"바이오식품공학과\", \"바이오생명공학과\", \"AI융합학부\"];\n");
      out.write("        var nursing = [\"간호학과\"];\n");
      out.write("        var health = [\"바이오신약의과학부\", \"바이오헬스융합학부\", \"스포츠과학부\"];\n");
      out.write("        var beauty = [\"의류산업학과\", \"뷰티산업학과\", \"소비자생활문화산업학과\"];\n");
      out.write("        var teach = [\"교육학과\", \"사회교육과\", \"윤리교육과\", \"한문교육과\", \"유아교육과\"];\n");
      out.write("        var art = [\"동양학과\", \"서양학과\", \"조소과\", \"공예과\", \"산업디자인과\"];\n");
      out.write("        var music = [\"성악과\", \"기악과\", \"작곡과\"];\n");
      out.write("        var culture = [\"문화예술경영학과\", \"미디어영상연기학과\", \"현대실용음악학과\", \"무용예술학과\"];\n");
      out.write("        var target = document.getElementById(\"userMajor\");\n");
      out.write("\n");
      out.write("        if (e.value == \"인문과학대학\") {\n");
      out.write("            var dept = humanities;\n");
      out.write("        } else if (e.value == \"사회과학대학\") {\n");
      out.write("            var dept = historic;\n");
      out.write("        } else if (e.value == \"법과대학\") {\n");
      out.write("            var dept = law;\n");
      out.write("        } else if (e.value == \"자연과학대학\") {\n");
      out.write("        	var dept = nature;\n");
      out.write("        } else if (e.value == \"지식서비스공과대학\") {\n");
      out.write("        	var dept = engineering;\n");
      out.write("        } else if (e.value == \"간호대학\") {\n");
      out.write("        	var dept = nursing;\n");
      out.write("        } else if (e.value == \"Health&WellnessCollege\") {\n");
      out.write("        	var dept = health;\n");
      out.write("        } else if (e.value == \"뷰티생활산업국제대학\") {\n");
      out.write("        	var dept = beauty;\n");
      out.write("        } else if (e.value == \"사범대학\") {\n");
      out.write("        	var dept = teach;\n");
      out.write("        } else if (e.value == \"미술대학\") {\n");
      out.write("        	var dept = art;\n");
      out.write("        } else if (e.value == \"음악대학\") {\n");
      out.write("        	var dept = music;\n");
      out.write("        } else if (e.value == \"뷰티생활산업국제대학\") {\n");
      out.write("        	var dept = beauty;\n");
      out.write("        } else {\n");
      out.write("        	var dept = culture;\n");
      out.write("        }\n");
      out.write("        target.options.length = 0;\n");
      out.write("        for (i in dept) {\n");
      out.write("            var opt = document.createElement(\"option\");\n");
      out.write("            opt.value = dept[i];\n");
      out.write("            opt.innerHTML = dept[i];\n");
      out.write("            target.appendChild(opt);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("	<script src = \"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\n");
      out.write("	<script src = \"js/bootstrap.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
